name: yata
description: "Inventory and order management system for small restaurants"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.2.1
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  json_annotation: ^4.9.0
  mutex: ^3.1.0
  google_fonts: ^6.2.1
  go_router: ^14.6.1
  lucide_icons: ^0.257.0
  shelf: ^1.4.2
  shelf_router: ^1.1.0
  # intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.8.0
  build_runner: ^2.5.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
