name: yata
description: "Inventory and order management system for small restaurants"
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.2.1
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  json_annotation: ^4.9.0
  mutex: ^3.1.0
  google_fonts: ^6.2.1
  go_router: ^16.1.0
  lucide_icons: ^0.257.0
  shelf: ^1.4.2
  shelf_router: ^1.1.0
  gotrue: ^2.13.0
  file_picker: ^8.1.6
  csv: ^6.0.0
  window_manager: ^0.5.1
  logger: ^2.0.2+1
  crypto: ^3.0.3
  archive: ^4.0.7
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  mocktail: ^1.0.3
  riverpod_lint: ^2.6.5
  json_serializable: ^6.8.0
  icons_launcher: ^3.0.3
  build_runner: ^2.5.4
  integration_test:
    sdk: flutter

  test: any

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    windows:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - .env
