name: Build Desktop Bundles (Tagged)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-desktop:
    name: Build ${{ matrix.build-target }} bundle
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-target: linux
            artifact-path: build/linux/x64/release/bundle
            artifact-name: yata-linux-bundle
          - os: windows-latest
            build-target: windows
            artifact-path: build/windows/runner/Release
            artifact-name: yata-windows-runner
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable desktop target
        if: matrix.build-target == 'linux'
        run: flutter config --enable-linux-desktop

      - name: Enable desktop target
        if: matrix.build-target == 'windows'
        run: flutter config --enable-windows-desktop

      - name: Install Linux build dependencies
        if: matrix.build-target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Fetch Flutter dependencies
        run: flutter pub get

      - name: Build release bundle
        run: flutter build ${{ matrix.build-target }} --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          if-no-files-found: error
